name: CI

on:
  push:
    branches-ignore:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run lint and tests
      run: |
        npm ci
        npm run lint
        npm test
        npm build
      env:
        CI: true
